name: Crash Report
description: Report a crash that occurred while playing the game.
labels: ["type: major bug", "status: pending triage"]
title: "Crash Report: "
body:
  - type: dropdown
    attributes:
      label: Platform
      description: Which platform are you playing on?
      options:
        - Github (Downloadable Build) - Windows
        - Compiled from GitHub Source Code
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: Which version of WITF are you playing on? The game version is in the bottom left corner of the main menu. 
      placeholder: ex. v0.9.0
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Describe the crash."

  - type: textarea
    attributes:
      label: Description
      description: Include screenshots or videos of the crash happening. Provide as much detail as you can. 
      placeholder: Describe the crash here...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: What steps can other people take to reliably trigger this crash?
      placeholder: 1. Open the game...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash logs
      description: These can be found in the logs folder where Funkin.exe is.
      placeholder: Upload your logs here...
    validations:
      required: true
